import assert from 'node:assert/strict'
import { test } from 'node:test'
import { detectHeaders, loadHeaderRules, loadHeadersModule, loadPageRules, runPageDetector } from './helpers/rule-harness.mjs'

const pageRules = loadPageRules(['page/website-programs-extra.json', 'page/website-programs-page.json', 'page/php-ecosystem-assets.json'])
const gen = content => `<html><head><meta name="generator" content="${content}"></head><body></body></html>`
const html = body => `<html><head></head><body>${body}</body></html>`

// 每条都取自程序源码或官方站点的真实页面片段
const pageCases = [
  ['Apache Answer', { html: gen('Answer 2.0.3 - https://github.com/apache/answer version 42c4f4ef') }],
  ['XiunoBBS', { resources: ['https://bbs.example.com/view/js/xiuno.js?1.0'] }],
  ['XiunoBBS', { html: '<html><head><meta name="author" content="XiunoBBS 4.0" /></head></html>' }],
  ['Symphony', { html: html(`<script>var Label = { symphonyLabel: '链滴', servePath: 'https://ld246.com' }</script>`) }],
  ['Misago', { resources: ['https://misago-project.org/static/misago/js/misago.dad297d40f9c.js'] }],
  ['Forem', { selectors: ['.crayons-btn'] }],
  ['ElkArte', { globals: ['elk_forum_action'] }],
  ['FUDforum', { globals: ['fud_msg_focus'] }],
  ['WoltLab Suite', { resources: ['https://www.woltlab.com/js/WoltLabSuite.Core.tiny.min.js?v=1789998304'] }],
  ['Question2Answer', { resources: ['https://www.question2answer.org/qa/qa-content/qa-global.js?1.8.6'] }],
  ['UBB.threads', { html: gen('UBB.threads 7.7.5') }],
  ['XMB Forum', { html: html('<!-- Powered by XMB 1.9.12 -->') }],
  ['Web Wiz Forums', { html: gen('Web Wiz Forums 12.07') }],
  ['YaBB', { html: html('Powered by <a href="https://www.yabbforum.com" target="_blank">YaBB 2.7.00</a>') }],
  ['NexusPHP', { html: gen('NexusPHP') }],
  ['Gnuboard', { globals: ['g5_js_ver'] }],
  ['XpressEngine', { html: gen('XpressEngine') }],
  ['Rhymix', { html: gen('Rhymix') }],
  ['Friendica', { html: gen('Friendica 2026.08-rc') }],
  ['Elgg', { resources: ['https://elgg.org/cache/1789033691/default/elgg.js'] }],
  ['Elgg', { globals: ['elgg'] }],
  ['HumHub', { resources: ['https://community.humhub.com/assets/82921540/js/humhub-app.js?v=1790083825'] }],
  ['HumHub', { globals: ['humhub'] }],
  ['HTMLy', { html: gen('HTMLy v3.1.1') }],
  ['b2evolution', { html: gen('b2evolution 7.3.0-PRO') }],
  ['Serendipity', { html: gen('Serendipity v.2.6.1') }],
  ['Nucleus CMS', { html: gen('Nucleus CMS v3.71') }],
  ['VanBlog', { selectors: ['.vanblog-main'] }],
  ['NotionNext', { html: '<html><head><meta name="generator" content="NotionNext" data-next-head=""/></head></html>' }],
  ['Chevereto', { html: gen('Chevereto 4.0.0') }],
  ['Chevereto', { resources: ['https://chevereto.com/content/themes/v4/lib/Peafowl/peafowl.min.js?a6a7a9fe'] }],
  ['Chevereto', { globals: ['CHEVERETO'] }],
  ['EasyImage', { resources: ['https://img.example.com/public/static/EasyImage.js'] }],
  ['Medium', { resources: ['https://cdn-client.medium.com/lite/static/manifest-3df6b82e.js'] }],
  ['Hashnode', { resources: ['https://cdn.hashnode.com/res/hashnode/image/upload/v1/abc.png'] }],
  ['Hashnode', { href: 'https://someone.hashnode.dev/post-1' }],
  ['Tistory', { resources: ['https://tistory1.daumcdn.net/tistory_admin/userblog/userblog-837e/static/pc/dist/index.js'] }],
  ['Tistory', { globals: ['TistoryBlog'] }],
  ['Hatena Blog', { resources: ['https://cdn.blog.st-hatena.com/js/hatenablog.js?version=6810a7'] }],
  ['LiveJournal', { href: 'https://someone.livejournal.com/12345.html' }],
  ['TypePad', { html: gen('http://www.typepad.com/') }],
  ['Gridsome', { html: '<html><head><meta data-vue-tag="ssr" name="generator" content="Gridsome v0.7.20"></head></html>' }],
  ['Lume', { html: '<html><head><meta content="Lume 3.3.2" name=generator></head></html>' }],
  ['Quarto', { html: gen('quarto-1.11.5') }],
  ['Quarto', { resources: ['https://quarto.org/site_libs/quarto-nav/quarto-nav.js'] }],
  ['Rspress', { html: gen('Rspress v2.0.22') }],
  ['Eleventy', { html: gen('Eleventy (Build Awesome) v4.0.0') }],
  ['Bridgetown', { resources: ['https://www.bridgetownrb.com/_bridgetown/static/index.3fd2.js'] }],
  ['Doxygen', { html: gen('Doxygen 1.19.0') }],
  ['Doxygen', { html: html('<!-- Generated by Doxygen 1.9.8 -->') }],
  ['Nextra', { selectors: ['.nextra-focus'] }],
  ['Nextra', { globals: ['__nextra_internal__'] }],
  ['MinDoc', { html: '<html><head><title>我的项目 - Powered by MinDoc</title></head></html>' }],
  ['ShowDoc', { html: html(`<script>window.DocConfig = { server: '../server/index.php?s=', lang: 'zh-cn' }</script>`) }],
  ['ShowDoc', { resources: ['https://doc.example.com/server/index.php?s=/api/page/info'] }],
  ['YApi', { html: html('<div id="yapi" style="height: 100%;"></div>') }],
  ['YApi', { selectors: ['div#yapi'] }],
  ['AList', { html: gen('AList V3') }],
  ['AList', { globals: ['ALIST'] }],
  ['TiddlyWiki', { html: gen('TiddlyWiki') }],
  ['Foswiki', { html: gen('Foswiki') }],
  ['Foswiki', { resources: ['https://foswiki.org/pub/System/JQueryPlugin/plugins/cycle/pkg.js?version=3'] }],
  ['TWiki', { resources: ['https://twiki.org/pub/TWiki/TWikiJavascripts/twikilib.js'] }],
  ['MoinMoin', { resources: ['https://moinmo.in/moin_static19/common/js/common.js'] }],
  ['PmWiki', { resources: ['https://www.pmwiki.org/pmwiki/pub/lib/pmwiki-core.css?v=5638'] }],
  ['WikkaWiki', { html: gen('WikkaWiki') }],
  ['YesWiki', { resources: ['https://yeswiki.net/javascripts/yeswiki-base.js'] }],
  ['YesWiki', { selectors: ['#yw-container'] }],
  ['PukiWiki', { resources: ['https://pukiwiki.example.jp/skin/pukiwiki.css'] }],
  ['Apache JSPWiki', { html: '<html lang="en" xmlns:jspwiki="http://jspwiki.apache.org"><head></head></html>' }],
  ['MetInfo', { html: gen('MetInfo V8.1" data-variable="|cn|cn|uitest|10001|10001|0') }],
  ['YzmCMS', { html: '<html><head><meta name="author" content="YzmCMS内容管理系统"></head></html>' }],
  ['YzmCMS', { resources: ['https://www.example.com/common/static/css/yzm-common.css'] }],
  ['DouPHP', { html: '<html><head><title>首页 - Powered by DouPHP</title></head></html>' }],
  ['CmsEasy', { html: '<html><head><meta name="Generator" content="CmsEasy 7_7_7_20250320_UTF8" /></head></html>' }],
  ['XunRuiCMS', { resources: ['https://www.xunruicms.com/api/language/zh-cn/lang.js'] }],
  ['EyouCMS', { html: gen('eyoucms') }],
  ['MacCMS', { html: html('<script>var maccms={"path":"","mid":"1","url":"www.example.com"};</script>') }],
  ['MacCMS', { globals: ['maccms'] }],
  ['DESTOON', { html: gen('DESTOON B2B - www.destoon.com') }],
  ['74cms', { globals: ['qscms'] }],
  ['FastAdmin', { resources: ['https://www.example.com/assets/js/require-frontend.min.js?v=1.5.0'] }],
  ['SiteServer CMS', { resources: ['https://sscms.com/sitefiles/resources/swiperjs/swiper-bundle.min.js'] }],
  ['JEECMS', { resources: ['https://www.jeecms.com/r/cms/www/default/js/front.js'] }],
  ['PublicCMS', { resources: ['https://download.publiccms.com/assets/js/cms.support.js'] }],
  ['MCMS', { resources: ['https://www.mingsoft.net/static/plugins/ms/3.2/ms.umd.js?t=20260616'] }],
  ['Jspxcms', { html: '<html><head><title>首页 - Powered by Jspxcms</title></head></html>' }],
  ['JPress', { resources: ['https://www.example.com/static/front/jpressfront.js'] }],
  ['RuoYi', { resources: ['https://demo.example.com/ruoyi/js/ry-ui.js?v=4.8.3'] }],
  ['WSTMart', { resources: ['https://shop.example.com/wstmart/home/view/default/js/common.js'] }],
  ['Backdrop CMS', { html: gen('Backdrop CMS 1 (https://backdropcms.org)') }],
  ['e107', { resources: ['https://d14cgbx38rqnr5.cloudfront.net/e107_web/cache/c55a6520.css'] }],
  ['XOOPS', { resources: ['https://xoops.org/include/xoops.js'] }],
  ['PHP-Nuke', { html: gen('PHP-Nuke Copyright (c) 2006 by Francisco Burzi') }],
  ['DataLife Engine', { html: gen('DataLife Engine (https://dle-news.ru)') }],
  ['1C-Bitrix', { resources: ['https://www.1c-bitrix.ru/bitrix/templates/1c_bitrix_2018/vendor/bootstrap/bootstrap.min.css'] }],
  ['Subrion CMS', { html: gen('Subrion CMS - Best PHP Open Source CMS') }],
  ['GetSimple CMS', { html: gen('GetSimple - 3.3.16') }],
  ['CMSimple', { html: gen('CMSimple 4.7') }],
  ['WebsiteBaker', { html: gen('WebsiteBaker') }],
  ['LEPTON CMS', { html: gen('LEPTON CMS') }],
  ['Mambo', { html: gen('Mambo - Copyright 2000 - 2008 Miro International Pty Ltd.') }],
  ['PyroCMS', { html: gen('PyroCMS') }],
  ['Omeka', { globals: ['Omeka'] }],
  ['WHMCS', { globals: ['WHMCS'] }],
  ['NamelessMC', { selectors: ["span.item > a[href*='//namelessmc.com']"] }],
  ['CubeCart', { html: gen('cubecart') }],
  ['X-Cart', { globals: ['xliteConfig'] }],
  ['Microsoft SharePoint', { html: gen('Microsoft SharePoint') }],
  ['Spree Commerce', { globals: ['Spree'] }],
  ['Solidus', { globals: ['Solidus'] }],
  ['LocomotiveCMS', { resources: ['https://cdn.locomotive.works/sites/5f/theme/stylesheets/app.css'] }],
  ['Etherpad', { resources: ['https://pad.example.org/static/plugins/ep_etherpad-lite/static/js/pad.js'] }],
  ['Dcat Admin', { resources: ['https://admin.example.com/vendor/dcat-admin/dcat/js/dcat-app.js?v2.2.2'] }],
  ['Weebly', { resources: ['https://cdn11.editmysite.com/js/site/main.js'] }],
  ['Jimdo', { resources: ['https://assets.jimstatic.com/web.js.9d2c.js'] }],
  ['Strikingly', { resources: ['https://static-assets.strikinglycdn.com/landing-new.css'] }],
  ['Strikingly', { html: html('<!-- Powered by Strikingly.com 4 (1) Sep 26, 2026 at 08:00 -->') }],
  ['Duda', { resources: ['https://dd-cdn.multiscreensite.com/runtime-react/main.js'] }],
  ['Google Sites', { href: 'https://sites.google.com/view/example/home' }],
  ['Webnode', { html: gen('Webnode') }]
]

test('新增网站程序在真实 page-detector 里按页面特征命中', async () => {
  for (const [name, fixture] of pageCases) {
    const technologies = await runPageDetector(pageRules, fixture)
    assert.ok(
      technologies.some(tech => tech.name === name),
      `${name} 未命中：${JSON.stringify(fixture).slice(0, 160)} => ${technologies.map(tech => tech.name).join(', ')}`
    )
  }
})

test('正文里提到程序名、通用路径和常见全局变量时不误判', async () => {
  const newNames = new Set(pageCases.map(([name]) => name))
  const technologies = await runPageDetector(pageRules, {
    href: 'https://blog.example.com/posts/1',
    html: html(
      [
        '<p>对比了 Answer、Medium、MetInfo、YApi、TiddlyWiki、Doxygen、Gridsome、NotionNext、Symphony 和 PbootCMS。</p>',
        '<p>generator 字段示例：content="Hexo"，路径 /static/js/home.js、/assets/js/require.js、/pub/lib/、/r/cms/</p>',
        '<a href="https://github.com/apache/answer">apache/answer</a> <a href="https://namelessmc.com">NamelessMC</a>',
        '<div id="yapi-doc"></div><title>Powered by DouPHP 教程</title>'
      ].join('')
    ),
    resources: [
      'https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js',
      'https://blog.example.com/static/js/home.js',
      'https://blog.example.com/assets/js/require.min.js',
      'https://blog.example.com/api/languages/list',
      'https://blog.example.com/static/misago-fan-art.png'
    ],
    globals: ['jQuery', 'Label', 'Config', 'config'],
    classes: ['btn', 'crayon', 'nextra', 'van-main']
  })
  // technologies 来自 vm 里的数组，先转成当前环境的数组再比较
  const wrong = Array.from(
    technologies.filter(tech => newNames.has(tech.name)),
    tech => tech.name
  )
  assert.deepEqual(wrong, [])
})

const headerCases = [
  ['PbootCMS', { 'x-powered-by': 'PbootCMS' }],
  ['PbootCMS', { 'set-cookie': 'PbootSystem=8b6c1ac25a0d0c2d; path=/; HttpOnly' }],
  ['DESTOON', { 'x-powered-by': 'DESTOON' }],
  ['ThinkCMF', { 'x-powered-by': 'ThinkCMF' }],
  ['PublicCMS', { 'x-powered-publiccms': 'V6' }],
  ['PublicCMS', { 'set-cookie': 'PUBLICCMS_USER=1_abc; path=/' }],
  ['e107', { 'x-powered-by': 'e107' }],
  ['e107', { 'set-cookie': ['PHPSESSID=1; path=/', 'e107_csrf=abc; path=/'] }],
  ['PHPFusion', { 'x-phpfusion': '9.10' }],
  ['PHPFusion', { 'x-powered-by': 'PHP-Fusion 9.10.30' }],
  ['Backdrop CMS', { 'x-backdrop-cache': 'HIT' }],
  ['Backdrop CMS', { 'x-generator': 'Backdrop CMS 1 (https://backdropcms.org)' }],
  ['Dotclear', { 'x-dotclear-static-cache': 'true' }],
  ['1C-Bitrix', { 'x-powered-cms': 'Bitrix Site Manager (a2b9c2d4)' }],
  ['1C-Bitrix', { 'set-cookie': 'BITRIX_SM_GUEST_ID=123; path=/' }],
  ['Subrion CMS', { 'x-powered-cms': 'Subrion CMS' }],
  ['PyroCMS', { 'x-streams-distribution': 'PyroCMS' }],
  ['Botble CMS', { 'set-cookie': 'botble_session=eyJpdiI6; path=/; httponly' }],
  ['Paymenter', { 'set-cookie': 'paymenter_session=eyJpdiI6; path=/' }],
  ['Azuriom', { 'set-cookie': 'azuriom_session=eyJpdiI6; path=/' }],
  ['Elgg', { 'set-cookie': 'Elgg=hbq2u8; path=/; HttpOnly' }],
  ['Serendipity', { 'set-cookie': 's9y_01649fbee596aa878c015658a9a746d6=abc; path=/' }],
  ['Misago', { 'set-cookie': 'misagocsrftoken=abc; Path=/; SameSite=Lax' }],
  ['Question2Answer', { 'set-cookie': 'qa_key=abc; path=/' }],
  ['Foswiki', { 'x-foswikiaction': 'view' }],
  ['Foswiki', { 'set-cookie': 'SFOSWIKISID=abc; path=/; HttpOnly' }],
  ['TWiki', { 'set-cookie': 'TWIKISID=abc; path=/' }],
  ['MoinMoin', { 'set-cookie': 'MOIN_SESSION_443_ROOT_moin=abc; path=/' }],
  ['Microsoft SharePoint', { microsoftsharepointteamservices: '16.0.0.24326' }],
  ['Microsoft SharePoint', { sprequestguid: 'a1b2c3d4-0000-1111-2222-333344445555' }],
  ['Jimdo', { 'x-jimdo-instance': 'abc' }],
  ['Strikingly', { 'set-cookie': '__strk_viewer_country=CN; path=/' }],
  ['Etherpad', { server: 'Etherpad 2.2.7 (1a2b3c4)' }],
  ['XMB Forum', { 'set-cookie': 'xmblvb=1790000000; path=/' }]
]

test('新增网站程序的响应头与 Cookie 规则按单个特征命中', async () => {
  const headersModule = await loadHeadersModule()
  const headerRules = loadHeaderRules()
  for (const [name, headers] of headerCases) {
    const technologies = detectHeaders(headersModule, headerRules, headers)
    assert.ok(
      technologies.some(tech => tech.name === name),
      `${name} 未命中：${JSON.stringify(headers)} => ${technologies.map(tech => tech.name).join(', ')}`
    )
  }

  const headerNames = new Set(headerCases.map(([name]) => name))
  const generic = detectHeaders(headersModule, headerRules, {
    server: 'nginx/1.25.3',
    'x-powered-by': 'PHP/8.3.2',
    'set-cookie': ['PHPSESSID=abc; path=/', 'laravel_session=abc; path=/', 'XSRF-TOKEN=abc; path=/', 'my_qa_key_backup=1; path=/'],
    'x-cache': 'HIT'
  })
  assert.deepEqual(
    generic.filter(tech => headerNames.has(tech.name)).map(tech => tech.name),
    []
  )
})
